import type { Meta, StoryObj } from '@storybook/react-vite'

/**
 * Border-width stories.
 *
 * 3 utilities ship: `border-q-thin`, `border-q-medium`, `border-q-thick`.
 * `border-none` intentionally skipped (would collide with Tailwind's
 * built-in `border-style: none`). Use Tailwind's native `border-0` for
 * zero width.
 *
 * Per-side variants (`border-q-l-thick` etc.) are auto-generated by
 * Tailwind v4 from the same `--border-width-*` tokens — no extra codegen.
 */

const VARIANTS = [
  { class: 'border-q-thin', label: 'border-q-thin', value: '1px' },
  { class: 'border-q-medium', label: 'border-q-medium', value: '1.5px' },
  { class: 'border-q-thick', label: 'border-q-thick', value: '2px' },
] as const

function All() {
  return (
    <section className="text-q-text-primary space-y-4">
      <div className="grid grid-cols-3 gap-3">
        {VARIANTS.map(v => (
          <div
            key={v.class}
            className={`${v.class} border-q-border-strong bg-q-background-primary rounded p-4 text-center`}
          >
            <code className="text-q-body-sm-regular">{v.label}</code>
            <div className="text-q-text-tertiary text-q-caption-sm-regular mt-1">{v.value}</div>
          </div>
        ))}
      </div>

      <div>
        <p className="text-q-text-secondary text-q-caption-sm-regular mb-2">
          Per-side variants (free via Tailwind v4):
        </p>
        <div className="grid grid-cols-3 gap-3">
          <div className="border-l-q-thick border-q-border-strong bg-q-background-primary rounded-r p-3 text-q-body-sm-regular">
            <code>border-l-q-thick</code>
          </div>
          <div className="border-t-q-medium border-q-border-strong bg-q-background-primary rounded-b p-3 text-q-body-sm-regular">
            <code>border-t-q-medium</code>
          </div>
          <div className="border-b-q-thin border-q-border-strong bg-q-background-primary rounded-t p-3 text-q-body-sm-regular">
            <code>border-b-q-thin</code>
          </div>
        </div>
      </div>
    </section>
  )
}

const meta: Meta<typeof All> = {
  title: 'Tokens/Border width',
  component: All,
  parameters: {
    docs: {
      description: {
        component:
          'Three width tokens (thin/medium/thick) in px units, plus per-side variants from Tailwind v4. Width is px, not rem — borders should not scale with font-size.',
      },
    },
  },
}

export default meta

type Story = StoryObj<typeof All>

export const Default: Story = {}
