import { describe, expect, it } from 'vitest'
import { mkTokens } from '../test-fixtures.ts'
import { primitivesBorderWidth, tailwindBorderWidth } from './border-width.ts'

describe('Output stability', () => {
  describe('primitivesBorderWidth', () => {
    it('emits --hf-border-width-* in px (not rem) — pixel-grid integrity for borders', () => {
      expect(primitivesBorderWidth(mkTokens())).toMatchInlineSnapshot(`
      "/**
       * Generated by quanta codegen — DO NOT EDIT.
       * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
       *
       * Source: @higgsfield-ai/design-tokens (Figma Variables).
       */

      :root {
        --hf-border-width-none: 0px;
        --hf-border-width-thin: 1px;
        --hf-border-width-medium: 1.5px;
        --hf-border-width-thick: 2px;
      }
      "
    `)
    })
  })

  describe('tailwindBorderWidth', () => {
    it('emits --border-width-* var refs; deliberately skips `none` (would collide with border-style)', () => {
      expect(tailwindBorderWidth(mkTokens())).toMatchInlineSnapshot(`
      "/**
       * Generated by quanta codegen — DO NOT EDIT.
       * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
       *
       * Source: @higgsfield-ai/design-tokens (Figma Variables).
       */

      @theme {
        --border-width-q-thin: var(--hf-border-width-thin);
        --border-width-q-medium: var(--hf-border-width-medium);
        --border-width-q-thick: var(--hf-border-width-thick);
      }
      "
    `)
    })
  })
})
