import { describe, expect, it } from 'vitest'
import { mkTokens } from '../test-fixtures.ts'
import { primitivesBreakpoint, tailwindBreakpoint } from './breakpoint.ts'

describe('Output stability', () => {
  describe('primitivesBreakpoint', () => {
    it('emits four --hf-breakpoint-* vars in fixed order (mobile..wide) as rem', () => {
      expect(primitivesBreakpoint(mkTokens())).toMatchInlineSnapshot(`
      "/**
       * Generated by quanta codegen — DO NOT EDIT.
       * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
       *
       * Source: @higgsfield-ai/design-tokens (Figma Variables).
       */

      :root {
        --hf-breakpoint-mobile: 20rem;
        --hf-breakpoint-tablet: 48rem;
        --hf-breakpoint-desktop: 80rem;
        --hf-breakpoint-wide: 120rem;
      }
      "
    `)
    })
  })

  describe('tailwindBreakpoint', () => {
    it('emits LITERAL rem (not var refs) — @media disallows var() in feature values; mobile skipped', () => {
      expect(tailwindBreakpoint(mkTokens())).toMatchInlineSnapshot(`
      "/**
       * Generated by quanta codegen — DO NOT EDIT.
       * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
       *
       * Source: @higgsfield-ai/design-tokens (Figma Variables).
       */

      @theme {
        --breakpoint-q-tablet: 48rem;
        --breakpoint-q-desktop: 80rem;
        --breakpoint-q-wide: 120rem;
      }
      "
    `)
    })
  })
})
