import { describe, expect, it } from 'vitest'
import { mkTokens } from '../test-fixtures.ts'
import { primitivesColor, tailwindColor, themeColor } from './color.ts'

describe('Output stability', () => {
  describe('primitivesColor', () => {
    it('emits :root block with --hf-color-* vars', () => {
      expect(primitivesColor(mkTokens())).toMatchInlineSnapshot(`
      "/**
       * Generated by quanta codegen — DO NOT EDIT.
       * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
       *
       * Source: @higgsfield-ai/design-tokens (Figma Variables).
       */

      :root {
        --hf-color-blue-500: #0066ff;

        --hf-color-grey-050: #f8f8f8;
        --hf-color-grey-900: #1a1a1a;
      }
      "
    `)
    })
  })

  describe('themeColor', () => {
    it('wraps light/dark blocks in @layer quanta-theme with :where() selectors', () => {
      expect(themeColor(mkTokens())).toMatchInlineSnapshot(`
      "/**
       * Generated by quanta codegen — DO NOT EDIT.
       * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
       *
       * Source: @higgsfield-ai/design-tokens (Figma Variables).
       */

      @layer quanta-theme {

        :where(:root),
        :where([data-theme="default-light"]) {
          color-scheme: light;

          --hf-color-background-primary: #ffffff;

          --hf-color-text-primary: var(--hf-color-grey-900);
        }

        :where([data-theme="default-dark"]) {
          color-scheme: dark;

          --hf-color-background-primary: var(--hf-color-grey-900);

          --hf-color-text-primary: #ffffff;
        }

      }
      "
    `)
    })
  })

  describe('tailwindColor', () => {
    it('emits two @theme inline blocks: semantic, then primitives', () => {
      expect(tailwindColor(mkTokens())).toMatchInlineSnapshot(`
      "/**
       * Generated by quanta codegen — DO NOT EDIT.
       * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
       *
       * Source: @higgsfield-ai/design-tokens (Figma Variables).
       */

      /* semantic → Tailwind */
      @theme inline {
        --color-q-background-primary: var(--hf-color-background-primary);

        --color-q-text-primary: var(--hf-color-text-primary);
      }

      /* primitives → Tailwind */
      @theme inline {
        --color-q-blue-500: var(--hf-color-blue-500);

        --color-q-grey-050: var(--hf-color-grey-050);
        --color-q-grey-900: var(--hf-color-grey-900);
      }
      "
    `)
    })
  })
})
