import { describe, expect, it } from 'vitest'
import { mkTokens } from '../test-fixtures.ts'
import { primitivesMotion, tailwindMotion } from './motion.ts'

describe('Output stability', () => {
  describe('primitivesMotion', () => {
    it('emits --hf-duration-* in ms and --hf-ease-* timing strings, semantic order', () => {
      expect(primitivesMotion(mkTokens())).toMatchInlineSnapshot(`
        "/**
         * Generated by quanta codegen — DO NOT EDIT.
         * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
         *
         * Source: @higgsfield-ai/design-tokens (Figma Variables).
         */

        :root {
          --hf-duration-instant: 0ms;
          --hf-duration-fast: 100ms;
          --hf-duration-normal: 200ms;
          --hf-duration-slow: 300ms;
          --hf-duration-slower: 500ms;
          --hf-ease-in: cubic-bezier(0.4, 0, 1, 1);
          --hf-ease-out: cubic-bezier(0, 0, 0.2, 1);
          --hf-ease-in-out: cubic-bezier(0.4, 0, 0.2, 1);
          --hf-ease-linear: linear;
        }
        "
      `)
    })
  })

  describe('tailwindMotion', () => {
    it('bridges duration via --transition-duration-q-* (Tailwind\'s real namespace) and easing via --ease-q-*', () => {
      expect(tailwindMotion(mkTokens())).toMatchInlineSnapshot(`
        "/**
         * Generated by quanta codegen — DO NOT EDIT.
         * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
         *
         * Source: @higgsfield-ai/design-tokens (Figma Variables).
         */

        @theme {
          --transition-duration-q-instant: var(--hf-duration-instant);
          --transition-duration-q-fast: var(--hf-duration-fast);
          --transition-duration-q-normal: var(--hf-duration-normal);
          --transition-duration-q-slow: var(--hf-duration-slow);
          --transition-duration-q-slower: var(--hf-duration-slower);
          --ease-q-in: var(--hf-ease-in);
          --ease-q-out: var(--hf-ease-out);
          --ease-q-in-out: var(--hf-ease-in-out);
          --ease-q-linear: var(--hf-ease-linear);
        }
        "
      `)
    })
  })
})
