import { describe, expect, it } from 'vitest'
import { mkTokens } from '../test-fixtures.ts'
import { primitivesRadius, tailwindRadius } from './radius.ts'

describe('Output stability', () => {
  describe('primitivesRadius', () => {
    it('emits --hf-radius-* numeric keys in rem; `full` as a 9999px sentinel (NOT rem)', () => {
      expect(primitivesRadius(mkTokens())).toMatchInlineSnapshot(`
        "/**
         * Generated by quanta codegen — DO NOT EDIT.
         * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
         *
         * Source: @higgsfield-ai/design-tokens (Figma Variables).
         */

        :root {
          --hf-radius-0: 0;
          --hf-radius-050: 0.125rem;
          --hf-radius-100: 0.25rem;
          --hf-radius-200: 0.5rem;
          --hf-radius-full: 9999px;
        }
        "
      `)
    })
  })

  describe('tailwindRadius', () => {
    it('emits --radius-q-* var refs (→ rounded-q-* utilities), full included', () => {
      expect(tailwindRadius(mkTokens())).toMatchInlineSnapshot(`
        "/**
         * Generated by quanta codegen — DO NOT EDIT.
         * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
         *
         * Source: @higgsfield-ai/design-tokens (Figma Variables).
         */

        @theme {
          --radius-q-0: var(--hf-radius-0);
          --radius-q-050: var(--hf-radius-050);
          --radius-q-100: var(--hf-radius-100);
          --radius-q-200: var(--hf-radius-200);
          --radius-q-full: var(--hf-radius-full);
        }
        "
      `)
    })
  })
})
