/**
 * Shared emit helpers — pure functions reused across category emitters.
 *
 * Anything that lives here must be:
 *   - category-agnostic (no color/typography/spacing/breakpoint specifics)
 *   - stable byte-output across calls (deterministic ordering)
 *   - free of side effects
 *
 * Per-category emit/<x>.ts owns CSS structure (selectors, blocks); this
 * module owns scalar transforms and ordering used by multiple categories.
 */

/** Boilerplate banner written at the top of every generated CSS file. */
export const HEADER = `/**
 * Generated by quanta codegen — DO NOT EDIT.
 * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
 *
 * Source: @higgsfield-ai/design-tokens (Figma Variables).
 */
`

/**
 * Convert a px-equivalent number to a rem string (assumes root font-size 16px).
 *   rem(0)    → "0"          (unitless — idiomatic CSS for zero)
 *   rem(4)    → "0.25rem"
 *   rem(16)   → "1rem"
 *   rem(-1.2) → "-0.075rem"
 *
 * Trailing-zero noise is dropped naturally by toString (1.25 → "1.25", 1.0 → "1").
 */
export function rem(n: number): string {
  if (n === 0)
    return '0'
  return `${n / 16}rem`
}

/**
 * Numeric-aware key sort. Integer-string keys ("1", "10", "200", "1300") sort
 * numerically, not lexicographically — `["1", "10", "2"]` would be unreadable.
 * Non-numeric keys ("primary", "tight") fall back to byte-order lexicographic.
 * Mixed groups put numerics first (matches "smallest first" intuition for scales).
 *
 * Uses byte comparison rather than localeCompare to keep output deterministic
 * across CI environments with different locales.
 */
export function sortedKeys(rec: Record<string, unknown>): string[] {
  return Object.keys(rec).sort((a, b) => {
    const na = /^\d+$/.test(a)
    const nb = /^\d+$/.test(b)
    if (na && nb)
      return Number(a) - Number(b)
    if (na !== nb)
      return na ? -1 : 1
    return a < b ? -1 : a > b ? 1 : 0
  })
}
