import { describe, expect, it } from 'vitest'
import { mkTokens } from '../test-fixtures.ts'
import { primitivesSpacing, tailwindSpacing } from './spacing.ts'

describe('Output stability', () => {
  describe('primitivesSpacing', () => {
    it('emits sorted --hf-space-* vars in rem', () => {
      expect(primitivesSpacing(mkTokens())).toMatchInlineSnapshot(`
      "/**
       * Generated by quanta codegen — DO NOT EDIT.
       * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
       *
       * Source: @higgsfield-ai/design-tokens (Figma Variables).
       */

      :root {
        --hf-space-4: 0.25rem;
        --hf-space-8: 0.5rem;
        --hf-space-16: 1rem;
      }
      "
    `)
    })
  })

  describe('tailwindSpacing', () => {
    it('emits additive q-prefixed named keys, never resets the shared --spacing base', () => {
      expect(tailwindSpacing(mkTokens())).toMatchInlineSnapshot(`
      "/**
       * Generated by quanta codegen — DO NOT EDIT.
       * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
       *
       * Source: @higgsfield-ai/design-tokens (Figma Variables).
       */

      @theme {
        --spacing-q-4: var(--hf-space-4);
        --spacing-q-8: var(--hf-space-8);
        --spacing-q-16: var(--hf-space-16);
      }
      "
    `)
    })
  })
})
