import { describe, expect, it } from 'vitest'
import { mkTokens } from '../test-fixtures.ts'
import { primitivesTypography, tailwindTypography, themeTypography } from './typography.ts'

describe('Output stability', () => {
  describe('primitivesTypography', () => {
    it('emits family / weight / letter-spacing primitives', () => {
      expect(primitivesTypography(mkTokens())).toMatchInlineSnapshot(`
      "/**
       * Generated by quanta codegen — DO NOT EDIT.
       * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
       *
       * Source: @higgsfield-ai/design-tokens (Figma Variables).
       */

      :root {
        --hf-type-family-mono-base: "Menlo";
        --hf-type-family-primary-base: "Inter";
        --hf-type-family-secondary-base: "Inter";

        --hf-type-weight-bold: 700;
        --hf-type-weight-medium: 500;
        --hf-type-weight-regular: 400;

        --hf-type-letter-spacing-loose: 0.03125rem;
        --hf-type-letter-spacing-none: 0;
        --hf-type-letter-spacing-tight: -0.03125rem;
      }
      "
    `)
    })
  })

  describe('themeTypography', () => {
    it('emits mobile-first base + @media tablet/desktop blocks for size & line-height', () => {
      expect(themeTypography(mkTokens())).toMatchInlineSnapshot(`
      "/**
       * Generated by quanta codegen — DO NOT EDIT.
       * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
       *
       * Source: @higgsfield-ai/design-tokens (Figma Variables).
       */

      :where(:root) {
        --hf-type-family-mono: var(--hf-type-family-mono-base), ui-monospace, monospace;
        --hf-type-family-primary: var(--hf-type-family-primary-base), system-ui, sans-serif;
        --hf-type-family-secondary: var(--hf-type-family-secondary-base), system-ui, sans-serif;

        --hf-type-size-400: 0.875rem;
        --hf-type-size-500: 1rem;

        --hf-type-line-height-400: 1.25rem;
        --hf-type-line-height-500: 1.5rem;
      }

      @media (min-width: 768px) {
        :where(:root) {
          --hf-type-size-400: 1rem;
          --hf-type-size-500: 1.125rem;
          --hf-type-line-height-400: 1.5rem;
          --hf-type-line-height-500: 1.75rem;
        }
      }

      @media (min-width: 1280px) {
        :where(:root) {
          --hf-type-size-400: 1.125rem;
          --hf-type-size-500: 1.25rem;
          --hf-type-line-height-400: 1.75rem;
          --hf-type-line-height-500: 2rem;
        }
      }
      "
    `)
    })
  })

  describe('tailwindTypography', () => {
    it('emits composite @utility text-q-{role}-{size}-{weight} utilities', () => {
      expect(tailwindTypography(mkTokens())).toMatchInlineSnapshot(`
      "/**
       * Generated by quanta codegen — DO NOT EDIT.
       * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
       *
       * Source: @higgsfield-ai/design-tokens (Figma Variables).
       */

      @utility text-q-body-md-regular {
        font-family:    var(--hf-type-family-primary);
        font-size:      var(--hf-type-size-500);
        font-weight:    var(--hf-type-weight-regular);
        line-height:    var(--hf-type-line-height-500);
        letter-spacing: var(--hf-type-letter-spacing-none);
      }
      "
    `)
    })
  })
})
