import { describe, expect, it } from 'vitest'
import { mkTokens } from '../test-fixtures.ts'
import { primitivesZIndex, tailwindZIndex } from './z-index.ts'

describe('Output stability', () => {
  describe('primitivesZIndex', () => {
    it('emits --hf-z-index-* vars in fixed semantic order (unitless integers)', () => {
      expect(primitivesZIndex(mkTokens())).toMatchInlineSnapshot(`
      "/**
       * Generated by quanta codegen — DO NOT EDIT.
       * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
       *
       * Source: @higgsfield-ai/design-tokens (Figma Variables).
       */

      :root {
        --hf-z-index-base: 0;
        --hf-z-index-dropdown: 10;
        --hf-z-index-sticky: 20;
        --hf-z-index-overlay: 30;
        --hf-z-index-modal: 40;
        --hf-z-index-popover: 50;
        --hf-z-index-toast: 60;
        --hf-z-index-tooltip: 70;
      }
      "
    `)
    })
  })

  describe('tailwindZIndex', () => {
    it('emits --z-index-* var refs to primitives', () => {
      expect(tailwindZIndex(mkTokens())).toMatchInlineSnapshot(`
      "/**
       * Generated by quanta codegen — DO NOT EDIT.
       * Regenerate via \`yarn workspace @higgsfield/quanta tokens:emit\`.
       *
       * Source: @higgsfield-ai/design-tokens (Figma Variables).
       */

      @theme {
        --z-index-q-base: var(--hf-z-index-base);
        --z-index-q-dropdown: var(--hf-z-index-dropdown);
        --z-index-q-sticky: var(--hf-z-index-sticky);
        --z-index-q-overlay: var(--hf-z-index-overlay);
        --z-index-q-modal: var(--hf-z-index-modal);
        --z-index-q-popover: var(--hf-z-index-popover);
        --z-index-q-toast: var(--hf-z-index-toast);
        --z-index-q-tooltip: var(--hf-z-index-tooltip);
      }
      "
    `)
    })
  })
})
