/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PersonalRouteImport } from './routes/personal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PersonalDomainRouteImport } from './routes/personal.$domain'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalRoute = PersonalRouteImport.update({
  id: '/personal',
  path: '/personal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonalDomainRoute = PersonalDomainRouteImport.update({
  id: '/$domain',
  path: '/$domain',
  getParentRoute: () => PersonalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/personal': typeof PersonalRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/personal/$domain': typeof PersonalDomainRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/personal': typeof PersonalRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/personal/$domain': typeof PersonalDomainRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/personal': typeof PersonalRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/personal/$domain': typeof PersonalDomainRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/personal'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/personal/$domain'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/personal' | '/robots.txt' | '/sitemap.xml' | '/personal/$domain'
  id:
    | '__root__'
    | '/'
    | '/personal'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/personal/$domain'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PersonalRoute: typeof PersonalRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal': {
      id: '/personal'
      path: '/personal'
      fullPath: '/personal'
      preLoaderRoute: typeof PersonalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/personal/$domain': {
      id: '/personal/$domain'
      path: '/$domain'
      fullPath: '/personal/$domain'
      preLoaderRoute: typeof PersonalDomainRouteImport
      parentRoute: typeof PersonalRoute
    }
  }
}

interface PersonalRouteChildren {
  PersonalDomainRoute: typeof PersonalDomainRoute
}

const PersonalRouteChildren: PersonalRouteChildren = {
  PersonalDomainRoute: PersonalDomainRoute,
}

const PersonalRouteWithChildren = PersonalRoute._addFileChildren(
  PersonalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PersonalRoute: PersonalRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
